In [1]:
import pandas as pd
import numpy as np

# Import dataset

In [2]:
data = pd.read_excel(r'C:\Users\user\Desktop\internship-project\dataset\Concrete_Data.xls')
data.head()

,Cement (component 1)(kg in a m^3 mixture),Blast Furnace Slag (component 2)(kg in a m^3 mixture),Fly Ash (component 3)(kg in a m^3 mixture),Water (component 4)(kg in a m^3 mixture),Superplasticizer (component 5)(kg in a m^3 mixture),Coarse Aggregate (component 6)(kg in a m^3 mixture),Fine Aggregate (component 7)(kg in a m^3 mixture),Age (day),"Concrete compressive strength(MPa, megapascals)"
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.986111
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.887366
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.269535
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.052780
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.296075

# Rename the columns

In [3]:
data = data.rename(columns={'Cement (component 1)(kg in a m^3 mixture)':"cement",
       'Blast Furnace Slag (component 2)(kg in a m^3 mixture)':"furnace_slag",
       'Fly Ash (component 3)(kg in a m^3 mixture)':"fly_ash",
       'Water  (component 4)(kg in a m^3 mixture)':"water",
       'Superplasticizer (component 5)(kg in a m^3 mixture)':"super_plasticizer",
       'Coarse Aggregate  (component 6)(kg in a m^3 mixture)':"coarse_agg",
       'Fine Aggregate (component 7)(kg in a m^3 mixture)':"fine_agg", 'Age (day)':"age",
       'Concrete compressive strength(MPa, megapascals) ':"compressive_strength"})

In [4]:
data.head(n=10)

,cement,furnace_slag,fly_ash,water,super_plasticizer,coarse_agg,fine_agg,age,compressive_strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.986111
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.887366
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.269535
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.052780
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.296075
5,266.0,114.0,0.0,228.0,0.0,932.0,670.0,90,47.029847
6,380.0,95.0,0.0,228.0,0.0,932.0,594.0,365,43.698299
7,380.0,95.0,0.0,228.0,0.0,932.0,594.0,28,36.447770
8,266.0,114.0,0.0,228.0,0.0,932.0,670.0,28,45.854291
9,475.0,0.0,0.0,228.0,0.0,932.0,594.0,28,39.289790

In [5]:
data.shape

(1030, 9)

# Outlier Analysis

In [6]:
from scipy import stats
z = np.abs(stats.zscore(data))
print(z)

[[2.47791782 0.85688631 0.84713204 ... 1.21765845 0.27973311 2.64519215]
 [2.47791782 0.85688631 0.84713204 ... 1.21765845 0.27973311 1.5612771 ]
 [0.49144303 0.79553263 0.84713204 ... 2.24091255 3.55306569 0.26660766]
 ...
 [1.2700575  0.75958527 0.85066095 ... 0.08012724 0.27973311 0.7259282 ]
 [1.16857975 1.3080724  0.84713204 ... 0.19118775 0.27973311 0.18264932]
 [0.19401043 0.30850389 0.37696733 ... 0.15072887 0.27973311 0.20461667]]

In [7]:
print(np.where(z > 3))

(array([  2,   3,   4,   6,  12,  17,  24,  25,  26,  30,  31,  33,  34,
        35,  41,  42,  56,  60,  61,  63,  65,  66,  76,  79,  99, 102,
       122, 125, 145, 148, 168, 171, 553, 559, 571, 584, 604, 610, 616,
       620, 622, 756, 769, 792, 798, 814, 820, 873, 936], dtype=int64), array([7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 1, 1, 1, 1, 7, 7, 7, 7, 7, 7, 7, 7,
       7, 7, 7, 3, 3], dtype=int64))

# Removing Outliers

In [8]:
z_scores = stats.zscore(data)

abs_z_scores = np.abs(z_scores)
filtered_entries = (abs_z_scores < 3).all(axis=1)
dataset = data[filtered_entries]

In [9]:
dataset.head(n=20)

,cement,furnace_slag,fly_ash,water,super_plasticizer,coarse_agg,fine_agg,age,compressive_strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.986111
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.887366
5,266.0,114.0,0.0,228.0,0.0,932.0,670.0,90,47.029847
7,380.0,95.0,0.0,228.0,0.0,932.0,594.0,28,36.447770
8,266.0,114.0,0.0,228.0,0.0,932.0,670.0,28,45.854291
9,475.0,0.0,0.0,228.0,0.0,932.0,594.0,28,39.289790
10,198.6,132.4,0.0,192.0,0.0,978.4,825.5,90,38.074244
11,198.6,132.4,0.0,192.0,0.0,978.4,825.5,28,28.021684
13,190.0,190.0,0.0,228.0,0.0,932.0,670.0,90,42.326932
14,304.0,76.0,0.0,228.0,0.0,932.0,670.0,28,47.813782
15,380.0,0.0,0.0,228.0,0.0,932.0,670.0,90,52.908320
16,139.6,209.4,0.0,192.0,0.0,1047.0,806.9,90,39.358048
18,380.0,95.0,0.0,228.0,0.0,932.0,594.0,90,40.563252
19,475.0,0.0,0.0,228.0,0.0,932.0,594.0,180,42.620648
20,427.5,47.5,0.0,228.0,0.0,932.0,594.0,180,41.836714
21,139.6,209.4,0.0,192.0,0.0,1047.0,806.9,28,28.237490
22,139.6,209.4,0.0,192.0,0.0,1047.0,806.9,3,8.063422
23,139.6,209.4,0.0,192.0,0.0,1047.0,806.9,180,44.207822
27,342.0,38.0,0.0,228.0,0.0,932.0,670.0,180,52.124386
28,427.5,47.5,0.0,228.0,0.0,932.0,594.0,28,37.427515

In [10]:
dataset.shape

(981, 9)

In [11]:
1030-49

981

    49 columns having outliers were removed and 'dataset' contain outlier free data

# Feature Engineering

    input variables / features  -> All the columns except 'compressive_strength'
    Response / Output variable  -> 'compressive_strength' column

In [12]:
X = dataset.iloc[:,0:8]
y = dataset.iloc[:,8]
X.head(n=10)

,cement,furnace_slag,fly_ash,water,super_plasticizer,coarse_agg,fine_agg,age
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28
5,266.0,114.0,0.0,228.0,0.0,932.0,670.0,90
7,380.0,95.0,0.0,228.0,0.0,932.0,594.0,28
8,266.0,114.0,0.0,228.0,0.0,932.0,670.0,28
9,475.0,0.0,0.0,228.0,0.0,932.0,594.0,28
10,198.6,132.4,0.0,192.0,0.0,978.4,825.5,90
11,198.6,132.4,0.0,192.0,0.0,978.4,825.5,28
13,190.0,190.0,0.0,228.0,0.0,932.0,670.0,90
14,304.0,76.0,0.0,228.0,0.0,932.0,670.0,28

In [13]:
y.head(n=10)

0     79.986111
1     61.887366
5     47.029847
7     36.447770
8     45.854291
9     39.289790
10    38.074244
11    28.021684
13    42.326932
14    47.813782
Name: compressive_strength, dtype: float64

# Normalization

In [14]:
from sklearn import preprocessing

minmax = preprocessing.MinMaxScaler(feature_range=(0,1))
X = minmax.fit(X).transform(X)

In [15]:
X

array([[1.        , 0.        , 0.        , ..., 0.69476744, 0.20572002,
        0.15083799],
       [1.        , 0.        , 0.        , ..., 0.73837209, 0.20572002,
        0.15083799],
       [0.37442922, 0.36064537, 0.        , ..., 0.38081395, 0.19066734,
        0.4972067 ],
       ...,
       [0.10616438, 0.44099968, 0.54272864, ..., 0.26569767, 0.46663322,
        0.15083799],
       [0.1303653 , 0.59063587, 0.        , ..., 0.54825581, 0.48896136,
        0.15083799],
       [0.36278539, 0.31793736, 0.39130435, ..., 0.18459302, 0.42022077,
        0.15083799]])

In [16]:
y[0:20]

0     79.986111
1     61.887366
5     47.029847
7     36.447770
8     45.854291
9     39.289790
10    38.074244
11    28.021684
13    42.326932
14    47.813782
15    52.908320
16    39.358048
18    40.563252
19    42.620648
20    41.836714
21    28.237490
22     8.063422
23    44.207822
27    52.124386
28    37.427515
Name: compressive_strength, dtype: float64

In [17]:
print(X.shape,y.shape)

(981, 8) (981,)

# Split data into train and test

In [18]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X,y,test_size=0.2)

In [19]:
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error

In [20]:
#model method is created to test the metrics of different regression algorithms

def model(algorithm,trainx,trainy,testx,testy):
    print (algorithm)
    algorithm.fit(trainx,trainy)
    train_prediction = algorithm.predict(trainx)
    test_prediction = algorithm.predict(testx)
    
    print ("\n**************************************** MEAN ABSOLUTE ERROR **********************************************\n")
    print ("MAE on training data :", mean_absolute_error(trainy,train_prediction))
    print ("MAE on test data :", mean_absolute_error(testy,test_prediction))
    ''' ----Find MAE difference between test data and training data----- '''
    mae_diff = mean_absolute_error(trainy,train_prediction) - mean_absolute_error(testy,test_prediction)
    print("Mean absolute error difference : {}".format(mae_diff))
    
    print ("\n************************************* ROOT MEAN SQUARED ERROR    ********************************************\n")
    print ("RMSE on training data :", np.sqrt(mean_squared_error(trainy,train_prediction)))
    print ("RMSE on test data :", np.sqrt(mean_squared_error(testy,test_prediction)))
    rmse_diff = np.sqrt(mean_squared_error(trainy,train_prediction)) - np.sqrt(mean_squared_error(testy,test_prediction))
    print("Root Mean Square Error difference : {}".format(rmse_diff))
    
    
    print ("\n************************************************ R2 - SCORE ************************************************\n")
    print ("R2 Score on training data :", r2_score(trainy,train_prediction))
    print ("R2 Score on test data :", r2_score(testy,test_prediction))
    r2_diff = r2_score(trainy,train_prediction) - r2_score(testy,test_prediction)
    print("R2 - Score difference : {}".format(r2_diff))
    
    
    print("\n************************************** NEW PREDICTIONS *****************************************************\n")
    new_pred = []
    #test the model by passing unseen data
    new_pred.append(algorithm.predict([[300.34,0.0,0.0,0.0,0.0,0.0,0.0,10]]))    
    new_pred.append(algorithm.predict([[300.34,0.0,0.0,0.0,0.0,0.0,0.0,10]]))
    new_pred.append(algorithm.predict([[329.34,116.0,0.0,300.9,3.9,1000.0,543.0,100]]))
    print(new_pred)

# Decision Tree Regression

In [21]:
from sklearn.tree import DecisionTreeRegressor

In [22]:
print("\n----------------------------------------- DECISION TREE REGRESSION ---------------------------------------------\n")

DT_regressor = DecisionTreeRegressor(random_state=0)
model(DT_regressor,x_train,y_train,x_test,y_test)

----------------------------------------- DECISION TREE REGRESSION ---------------------------------------------

DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
                      max_leaf_nodes=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      presort=False, random_state=0, splitter='best')

**************************************** MEAN ABSOLUTE ERROR **********************************************

MAE on training data : 0.07935925713297273
MAE on test data : 3.8121074708273084
Mean absolute error difference : -3.7327482136943355

************************************* ROOT MEAN SQUARED ERROR    ********************************************

RMSE on training data : 0.9854849675877794
RMSE on test data : 5.869418275674594
Root Mean Square Error difference : -4.883933308086815

************************************************ R2 - SCORE ************************************************

R2 Score on training data : 0.9965439596666278
R2 Score on test data : 0.8744191803716475
R2 - Score difference : 0.12212477929498033

************************************** NEW PREDICTIONS *****************************************************

[array([79.98611076]), array([79.98611076]), array([65.90701084])]

# Random Forest Regressor

In [23]:
from sklearn.ensemble import RandomForestRegressor

In [24]:
print("\n----------------------------------------- RANDOM FOREST REGRESSION -----------------------------------------------\n")

RF_regressor = RandomForestRegressor(n_estimators = 100, random_state = 0)
model(RF_regressor,x_train,y_train,x_test,y_test)

----------------------------------------- RANDOM FOREST REGRESSION -----------------------------------------------

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
                      max_features='auto', max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, n_estimators=100,
                      n_jobs=None, oob_score=False, random_state=0, verbose=0,
                      warm_start=False)

**************************************** MEAN ABSOLUTE ERROR **********************************************

MAE on training data : 1.3321872320562758
MAE on test data : 3.3057241720470785
Mean absolute error difference : -1.9735369399908027

************************************* ROOT MEAN SQUARED ERROR    ********************************************

RMSE on training data : 2.0493271542129072
RMSE on test data : 4.630028794478033
Root Mean Square Error difference : -2.5807016402651257

************************************************ R2 - SCORE ************************************************

R2 Score on training data : 0.9850548119683028
R2 Score on test data : 0.9218551112684078
R2 - Score difference : 0.063199700699895

************************************** NEW PREDICTIONS *****************************************************

[array([65.02466082]), array([65.02466082]), array([64.41092475])]

# Extra Tree Regressor

In [25]:
from sklearn.ensemble import ExtraTreesRegressor

In [26]:
print("\n------------------------------------------- EXTRA TREE REGRESSION -----------------------------------------------\n")

XT_regressor = ExtraTreesRegressor(n_estimators = 10, random_state = 0)
model(XT_regressor,x_train,y_train,x_test,y_test)

------------------------------------------- EXTRA TREE REGRESSION -----------------------------------------------

ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
                    max_features='auto', max_leaf_nodes=None,
                    min_impurity_decrease=0.0, min_impurity_split=None,
                    min_samples_leaf=1, min_samples_split=2,
                    min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
                    oob_score=False, random_state=0, verbose=0,
                    warm_start=False)

**************************************** MEAN ABSOLUTE ERROR **********************************************

MAE on training data : 0.07935925713297659
MAE on test data : 2.9394927123464663
Mean absolute error difference : -2.86013345521349

************************************* ROOT MEAN SQUARED ERROR    ********************************************

RMSE on training data : 0.9854849675877794
RMSE on test data : 4.55612283492134
Root Mean Square Error difference : -3.570637867333561

************************************************ R2 - SCORE ************************************************

R2 Score on training data : 0.9965439596666278
R2 Score on test data : 0.9243299463463749
R2 - Score difference : 0.0722140133202529

************************************** NEW PREDICTIONS *****************************************************

[array([65.67851849]), array([65.67851849]), array([56.38018606])]

# Gradient Boosting Regressor

In [27]:
from sklearn.ensemble import GradientBoostingRegressor

In [28]:
print("\n---------------------------------------- GRADIENT BOOSTING REGRESSION --------------------------------------------\n")

GB_regressor = GradientBoostingRegressor()
model(GB_regressor,x_train,y_train,x_test,y_test)

---------------------------------------- GRADIENT BOOSTING REGRESSION --------------------------------------------

GradientBoostingRegressor(alpha=0.9, criterion='friedman_mse', init=None,
                          learning_rate=0.1, loss='ls', max_depth=3,
                          max_features=None, max_leaf_nodes=None,
                          min_impurity_decrease=0.0, min_impurity_split=None,
                          min_samples_leaf=1, min_samples_split=2,
                          min_weight_fraction_leaf=0.0, n_estimators=100,
                          n_iter_no_change=None, presort='auto',
                          random_state=None, subsample=1.0, tol=0.0001,
                          validation_fraction=0.1, verbose=0, warm_start=False)

**************************************** MEAN ABSOLUTE ERROR **********************************************

MAE on training data : 2.861030677869904
MAE on test data : 3.7497448189627254
Mean absolute error difference : -0.8887141410928212

************************************* ROOT MEAN SQUARED ERROR    ********************************************

RMSE on training data : 3.8090207443724573
RMSE on test data : 5.145836821112483
Root Mean Square Error difference : -1.3368160767400257

************************************************ R2 - SCORE ************************************************

R2 Score on training data : 0.9483696023460405
R2 Score on test data : 0.9034737990373138
R2 - Score difference : 0.04489580330872667

************************************** NEW PREDICTIONS *****************************************************

[array([63.46383144]), array([63.46383144]), array([76.20801649])]

# ---------------------------------------    Evaluation   ----------------------------------------

    The three important metrics to evaluate the performance of regression models are:
    
    -> R2_Score (Accuracy)
    -> RMSE (Root Mean Square Error)
    -> MAE (Mean Absolute Error)

    A best model should have :
    
    -> More Accuracy(R2-score)
    -> Less RMSE and MAE
    
    Note:
     ** Accuracy(R2-score) of the test data should be higher than that of training data.
     ** RMSE or MAE of the test data should be less than that of training data.

In [74]:
#create a dataframe to compare the performance of each model

data = [
        ['Decision Tree Regressor', -3.73, -4.88, 99.65, 87.44, 12.21],
        ['Random Forest Regressor', -1.97, -2.58, 98.51, 92.91, 6.32],
        ['Extra Tree Regressor', -2.86, -3.57, 99.65, 92.43, 7.22],
        ['Gradient Boosting Regressor', -0.89, -1.34, 94.84, 90.35, 4.49]]
results = pd.DataFrame(data, columns=['Regressor', 
                                      'MAE difference',  
                                      'RMSE difference', 
                                      'R2-Score on train data',
                                      'R2-Score on test data',
                                      'R2-Score difference'])

In [75]:
results

,Regressor,MAE difference,RMSE difference,R2-Score on train data,R2-Score on test data,R2-Score difference
0,Decision Tree Regressor,-3.73,-4.88,99.65,87.44,12.21
1,Random Forest Regressor,-1.97,-2.58,98.51,92.91,6.32
2,Extra Tree Regressor,-2.86,-3.57,99.65,92.43,7.22
3,Gradient Boosting Regressor,-0.89,-1.34,94.84,90.35,4.49

In [76]:
results.style.background_gradient(cmap='pink_r')

    1) Decision Tree Regressor :
    
            -> It has accuracy of 99.65%, but it drastically decreased on test data to 87.44% 
               Hence it is not efficient
               
    2) Random Forest Regressor :
    
            -> It has accuracy of 98.51% on training data and 92.91% on test data. The accuracy decreased on test data.
            -> But RMSE(-2.58) and MAE(-1.97) have only slight differences between the train and test data.
            -> compared to decision tree, random forest is better
            
    3) Extra Tree Regressor :
    
            -> It has accuracy of 99.65% on training data and 92.43% on test data.There is a difference of 7.22 between 
               the accuracies. The accuracy decreased on test data. RMSE and MAE differences are also high.
               
    4) Gradient Boosting Regressor :
    
            -> It has accuracy of 94.84% on training data and 90.35% on test data.
            -> Its accuracy on training data is less, however, the accuracy on test data has no much difference.
            -> RMSE and MAE error differences are also less.
            -> It gave better results when tested on new data.
   
# conclusion:

    Hence Random Forest and Gradient Boosting best suited to this data. Moreover, gradient boosting predicted correctly 
    when exposed to new data

    NOTE : The metric values might differ from each run